### PR TITLE
Allow setting the format in the scaling options

### PR DESCRIPTION
**Pull request by hamoid**
This implements https://github.com/tomitrescak/meteor-uploads/issues/85 and allows you to make sure that thumbnails always have the desired file format (typically jpeg), independently of the original file format.

### CODE REVIEW

**Comment by tomitrescak** [comment]
Thanks for the PR! I have a question. What does following line do? Why is there '[0]'

+          srcPath: currentFolder + '/' + newFileName + '[0]',

**Comment by hamoid** [comment]
I should have left a comment in the code. What it does is selecting the first frame when you upload an animated gif. If you don't do that, you end up having one image per frame on the server (potentially tens or hundreds of images). When you upload a non animated image format, it has no effect. Basically it's a "protection against animated gifs" :)

**Comment by hamoid** [comment]
You can easily try what happens without it. Remove the '[0]', upload an animated gif, and check out the .upload directory.

**Comment by hamoid** [comment]
Closing, very old PR

**Pull request closed without merging**
