### PR TITLE
Update upload_server.js

### PR DESCRIPTION
**Pull request by msj121**
I think this will fix https://github.com/tomitrescak/meteor-uploads/issues/220

### CODE REVIEW

**Comment by rvetere** [comment]
please merge this!

**Comment by tomitrescak** [comment]
I've done it differently, but resolves the same problem. New version was published.

**Comment by rvetere** [comment]
Awesome, thanks a lot! 👍

**Comment by msj121** [comment]
@tomitrescak This is still not fixed, I have updated to the new version and the same fix works as far as I can tell...

Please see https://github.com/tomitrescak/meteor-tomi-upload-server/issues/34 for confirmation that the bug persists....

**Comment by msj121** [comment]
Sadly, I think there is a typo in this pull request... it should be:

+"/"+

**Comment by msj121** [comment]
@tomitrescak Please add me as a code collaborator if this is going to be deprecated as well. Thanks.

**Comment by tomitrescak** [comment]
I just did. All yours ;) thanks for taking over.

**Pull request closed without merging**
